In [3]:
import sklearn as sk
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score

In [4]:
houseprice=pd.read_csv(r'C:\Users\fakhr\Experimental_design_for_data_analysis\Dataset\kc_house_cleaned.csv')

In [6]:
y=np.array(houseprice['price'], dtype='float64')    # Converts y to an array  and y is our dataset which has the outputs

In [7]:
y.shape

(21611,)

In [8]:
y=y.reshape(-1,1)     #converts y to a 2D array
y.shape

(21611, 1)

In [9]:
x=houseprice.drop('price',axis=1)

In [11]:
x=np.array(x)

In [12]:
x.shape, y.shape    #both are 2D arrays. 2D array is required for our linear regression model

((21611, 16), (21611, 1))

In [14]:
kf = KFold(n_splits=3)    #var will be used to split the data to 3 subsets

In [15]:
list(kf.split(x))    # splits our x array into 3 arrays.  2 will be used to train and one will be used to test

[(array([ 7204,  7205,  7206, ..., 21608, 21609, 21610]),
  array([   0,    1,    2, ..., 7201, 7202, 7203])),
 (array([    0,     1,     2, ..., 21608, 21609, 21610]),
  array([ 7204,  7205,  7206, ..., 14405, 14406, 14407])),
 (array([    0,     1,     2, ..., 14405, 14406, 14407]),
  array([14408, 14409, 14410, ..., 21608, 21609, 21610]))]

In [16]:
i=1                   
for train,test in kf.split(x):
    print("\nTrain"+str(i),train)
    print("Test"+str(i),test)
    i+=1
    
 # it automatically turns the data into training and testing. All except one are used to train the model, 
 # whereas one is used to test the mode. Can be seen in below output


Train1 [ 7204  7205  7206 ... 21608 21609 21610]
Test1 [   0    1    2 ... 7201 7202 7203]

Train2 [    0     1     2 ... 21608 21609 21610]
Test2 [ 7204  7205  7206 ... 14405 14406 14407]

Train3 [    0     1     2 ... 14405 14406 14407]
Test3 [14408 14409 14410 ... 21608 21609 21610]


In [17]:
len(x), len(train), len(test)      # this shows how train and test is created using KFold function

(21611, 14408, 7203)

In [18]:
 # we will train our model with only one training and test data

kf=KFold(n_splits=2)
indices_list=list(kf.split(x))
indices_list

[(array([10806, 10807, 10808, ..., 21608, 21609, 21610]),
  array([    0,     1,     2, ..., 10803, 10804, 10805])),
 (array([    0,     1,     2, ..., 10803, 10804, 10805]),
  array([10806, 10807, 10808, ..., 21608, 21609, 21610]))]

In [20]:
indices_list[1]

(array([    0,     1,     2, ..., 10803, 10804, 10805]),
 array([10806, 10807, 10808, ..., 21608, 21609, 21610]))

In [22]:
x_train1, y_train1 = x[indices_list[0][0]], y[indices_list[0][0]]
x_test1, y_test1 = x[indices_list[0][1]], y[indices_list[0][1]]

x_train2, y_train2 = x[indices_list[1][0]], y[indices_list[1][0]]
x_test2, y_test2 = x[indices_list[1][1]], y[indices_list[1][1]]

In [23]:
x_test1.shape, y_test1.shape

((10806, 16), (10806, 1))

In [26]:
x_train1.shape, y_train1.shape

((10805, 16), (10805, 1))

In [27]:
reg=LinearRegression().fit(x_train1, y_train1)
reg.score(x_test1, y_test1)

0.6394506691446753

In [33]:
reg=LinearRegression().fit(x_train2, y_train2)
reg.score(x_test2, y_test2)

0.6440439140053222

In [32]:
cross_val_score(reg,x,y,cv=2)    # similar to what we did above but more easy. If you see the score matches as well

array([0.63945067, 0.64404391])