In [1]:
import sklearn as sk
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, RepeatedKFold
from sklearn.linear_model import LinearRegression

In [2]:
houseprice=pd.read_csv(r'C:\Users\fakhr\Experimental_design_for_data_analysis\Dataset\kc_house_cleaned.csv')

In [3]:
y=(np.array(houseprice['price'], dtype='float64')).reshape(-1,1)

In [4]:
x=houseprice.drop('price',axis=1)
x=np.array(x)

In [8]:
rkf= RepeatedKFold(n_splits=2, n_repeats=1, random_state=0)
indices_list=list(rkf.split(x))
indices_list

[(array([    4,     6,    10, ..., 21602, 21604, 21607]),
  array([    0,     1,     2, ..., 21608, 21609, 21610])),
 (array([    0,     1,     2, ..., 21608, 21609, 21610]),
  array([    4,     6,    10, ..., 21602, 21604, 21607]))]

In [9]:
i=1
for train,test in rkf.split(x):
    print('\nTrain'+str(i), train)
    print('Test'+str(i),test)
    
    i+=1


Train1 [    4     6    10 ... 21602 21604 21607]
Test1 [    0     1     2 ... 21608 21609 21610]

Train2 [    0     1     2 ... 21608 21609 21610]
Test2 [    4     6    10 ... 21602 21604 21607]


In [7]:
len(x), len(train), len(test)

(21611, 10806, 10805)

In [10]:
x_train1, y_train1 = x[indices_list[0][0]], y[indices_list[0][0]]
x_test1, y_test1 = x[indices_list[0][1]], y[indices_list[0][1]]

x_train2, y_train2 = x[indices_list[1][0]], y[indices_list[1][0]]
x_test2, y_test2 = x[indices_list[1][1]], y[indices_list[1][1]]

In [11]:
reg=LinearRegression().fit(x_train1, y_train1)
reg.score(x_test1, y_test1)

0.645816320441543

In [12]:
reg=LinearRegression().fit(x_train2, y_train2)
reg.score(x_test2, y_test2)

0.649843112118839

In [14]:
cross_val_score(reg,x,y,cv=rkf)    # similar to what we did above but more easy. If you see the score matches as well

array([0.64581632, 0.64984311])